//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangThuCung
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhSanPham
    {
        public int MaHinh { get; set; }
        public string MoTaHinh { get; set; }
        public int MaSP { get; set; }
        public byte[] HinhSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
